In [38]:
import pandas as pd
import numpy as np

In [254]:
clinical_breakpoints = pd.read_csv(f"./data/amr-r/clinical_breakpoints.txt", delimiter="\t")
clinical_breakpoints.head(20)

,guideline,type,host,method,site,mo,rank_index,ab,ref_tbl,disk_dose,breakpoint_S,breakpoint_R,uti,is_SDD
0,EUCAST 2024,human,human,DISK,NaN,B_ACHRMB_XYLS,2.0,MEM,A. xylosoxidans,10ug,26.0000,20.000,False,False
1,EUCAST 2024,human,human,MIC,NaN,B_ACHRMB_XYLS,2.0,MEM,A. xylosoxidans,NaN,1.0000,4.000,False,False
2,EUCAST 2024,human,human,DISK,NaN,B_ACHRMB_XYLS,2.0,SXT,A. xylosoxidans,1.25ug/23.75ug,26.0000,26.000,False,False
3,EUCAST 2024,human,human,MIC,NaN,B_ACHRMB_XYLS,2.0,SXT,A. xylosoxidans,NaN,0.1250,0.125,False,False
4,EUCAST 2024,human,human,DISK,NaN,B_ACHRMB_XYLS,2.0,TZP,A. xylosoxidans,30ug/6ug,26.0000,26.000,False,False
5,EUCAST 2024,human,human,MIC,NaN,B_ACHRMB_XYLS,2.0,TZP,A. xylosoxidans,NaN,4.0000,4.000,False,False
6,EUCAST 2024,human,human,DISK,NaN,B_ACNTB,3.0,AMK,Acinetobacter spp.,30ug,19.0000,19.000,False,False
7,EUCAST 2024,human,human,DISK,Uncomplicated urinary tract infection,B_ACNTB,3.0,AMK,Acinetobacter spp.,30ug,19.0000,19.000,True,False
8,EUCAST 2024,human,human,MIC,NaN,B_ACNTB,3.0,AMK,Acinetobacter spp.,NaN,8.0000,8.000,False,False
9,EUCAST 2024,human,human,MIC,Uncomplicated urinary tract infection,B_ACNTB,3.0,AMK,Acinetobacter spp.,NaN,8.0000,8.000,True,False
10,EUCAST 2024,human,human,DISK,NaN,B_ACNTB,3.0,CIP,Acinetobacter spp.,5ug,50.0000,21.000,False,False
11,EUCAST 2024,human,human,MIC,NaN,B_ACNTB,3.0,CIP,Acinetobacter spp.,NaN,0.0001,1.000,False,False
12,EUCAST 2024,human,human,MIC,NaN,B_ACNTB,3.0,COL,Acinetobacter spp.,NaN,2.0000,2.000,False,False
13,EUCAST 2024,human,human,DISK,NaN,B_ACNTB,3.0,DOR,Acinetobacter spp.,10ug,50.0000,22.000,False,False
14,EUCAST 2024,human,human,MIC,NaN,B_ACNTB,3.0,DOR,Acinetobacter spp.,NaN,0.0001,2.000,False,False
15,EUCAST 2024,human,human,DISK,NaN,B_ACNTB,3.0,GEN,Acinetobacter spp.,10ug,17.0000,17.000,False,False
16,EUCAST 2024,human,human,DISK,Uncomplicated urinary tract infection,B_ACNTB,3.0,GEN,Acinetobacter spp.,10ug,17.0000,17.000,True,False
17,EUCAST 2024,human,human,MIC,NaN,B_ACNTB,3.0,GEN,Acinetobacter spp.,NaN,4.0000,4.000,False,False
18,EUCAST 2024,human,human,MIC,Uncomplicated urinary tract infection,B_ACNTB,3.0,GEN,Acinetobacter spp.,NaN,4.0000,4.000,True,False
19,EUCAST 2024,human,human,DISK,NaN,B_ACNTB,3.0,IPM,Acinetobacter spp.,10ug,24.0000,21.000,False,False

In [233]:
antivirals = pd.read_csv(f"./data/amr-r/antivirals.txt", delimiter="\t")
antivirals.head(2)

,av,name,atc,cid,atc_group,synonyms,oral_ddd,oral_units,iv_ddd,iv_units,loinc
0,ABA,Abacavir,J05AF06,441300.0,Nucleoside and nucleotide reverse transcriptas...,"abacavir sulfate,avacavir,ziagen",0.6,g,NaN,NaN,"29113-8,30273-7,30287-7,30303-2,78772-1,78773-..."
1,ACI,Aciclovir,J05AB01,135398513.0,Nucleosides and nucleotides excl. reverse tran...,"acicloftal,aciclovier,aciclovirum,activir,acyc...",4.0,g,4.0,g,NaN

In [234]:
antibiotics = pd.read_csv(f"./data/amr-r/antibiotics.txt", delimiter="\t")
antibiotics.head(2)

,ab,cid,name,group,atc,atc_group1,atc_group2,abbreviations,synonyms,oral_ddd,oral_units,iv_ddd,iv_units,loinc
0,AMA,4649.0,4-aminosalicylic acid,Antimycobacterials,J04AA01,Drugs for treatment of tuberculosis,Aminosalicylic acid and derivatives,NaN,"aminopar,aminosalicylic,aminosalicylicacid,ami...",12.0,g,NaN,NaN,NaN
1,ACM,6450012.0,Acetylmidecamycin,Macrolides/lincosamides,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [235]:
dosage = pd.read_csv(f"./data/amr-r/dosage.txt", delimiter="\t")
dosage.head(2)

,ab,name,type,dose,dose_times,administration,notes,original_txt,eucast_version
0,AMK,Amikacin,standard_dosage,25-30 mg/kg,1.0,iv,NaN,25-30 mg/kg x 1 iv,13
1,AMX,Amoxicillin,high_dosage,2 g,6.0,iv,NaN,2 g x 6 iv,13

In [240]:
intrinsic_resistant = pd.read_csv(f"./data/amr-r/intrinsic_resistant.txt", delimiter="\t")
intrinsic_resistant.tail(5)

             microorganism      antibiotic
301578  Zongyangia hominis       Aztreonam
301579  Zongyangia hominis        Colistin
301580  Zongyangia hominis  Nalidixic acid
301581  Zongyangia hominis     Polymyxin B
301582  Zongyangia hominis      Temocillin

In [251]:
microorganism_codes = pd.read_csv(f"./data/amr-r/microorganisms.codes.txt", delimiter="\t")
microorganism_codes.tail(4)

        code              mo
4967     YZG  F_MYRZY_GLLR-C
4968     YZH    F_MYRZY_CRPP
4969     ZYM        B_PRPNSP
4970  ZYMSPP        B_PRPNSP

In [252]:
microorganism_groups = pd.read_csv(f"./data/amr-r/microorganisms.groups.txt", delimiter="\t")
microorganism_groups.tail(5)

,mo_group,mo,mo_group_name,mo_name
516,B_YERSN_PSDT-C,B_YERSN_PSDT,Yersinia pseudotuberculosis complex,Yersinia pseudotuberculosis
517,B_YERSN_PSDT-C,B_YERSN_PSTS,Yersinia pseudotuberculosis complex,Yersinia pseudotuberculosis pestis
518,B_YERSN_PSDT-C,B_YERSN_PSDT,Yersinia pseudotuberculosis complex,Yersinia pseudotuberculosis pseudotuberculosis
519,B_YERSN_PSDT-C,B_YERSN_SMLS,Yersinia pseudotuberculosis complex,Yersinia similis
520,B_YERSN_PSDT-C,B_YERSN_WTRS,Yersinia pseudotuberculosis complex,Yersinia wautersii

In [244]:
microorganisms = pd.read_csv(f"./data/amr-r/microorganisms.txt", delimiter="\t")
microorganisms.head(5)

,mo,fullname,status,kingdom,phylum,class,order,family,genus,species,...,lpsn_parent,lpsn_renamed_to,mycobank,mycobank_parent,mycobank_renamed_to,gbif,gbif_parent,gbif_renamed_to,prevalence,snomed
0,B_GRAMN,(unknown Gram-negatives),unknown,Bacteria,(unknown phylum),(unknown class),(unknown order),(unknown family),(unknown genus),(unknown species),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
1,B_GRAMP,(unknown Gram-positives),unknown,Bacteria,(unknown phylum),(unknown class),(unknown order),(unknown family),(unknown genus),(unknown species),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
2,B_ANAER-NEG,(unknown anaerobic Gram-negatives),unknown,Bacteria,(unknown phylum),(unknown class),(unknown order),(unknown family),(unknown genus),(unknown species),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
3,B_ANAER-POS,(unknown anaerobic Gram-positives),unknown,Bacteria,(unknown phylum),(unknown class),(unknown order),(unknown family),(unknown genus),(unknown species),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
4,B_ANAER,(unknown anaerobic bacteria),unknown,Bacteria,(unknown phylum),(unknown class),(unknown order),(unknown family),(unknown genus),(unknown species),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN

In [246]:
loinc = pd.read_csv(f"./data/amr-r/Loinc.csv", delimiter=",")

/tmp/ipykernel_98024/1066246570.py:1: DtypeWarning: Columns (8,15,16,17,22,36,38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  loinc = pd.read_csv(f"./data/amr-r/Loinc.csv", delimiter=",")

In [247]:
loinc.head(5)

,LOINC_NUM,COMPONENT,PROPERTY,TIME_ASPCT,SYSTEM,SCALE_TYP,METHOD_TYP,CLASS,VersionLastChanged,CHNG_TYPE,...,COMMON_ORDER_RANK,COMMON_SI_TEST_RANK,HL7_ATTACHMENT_STRUCTURE,EXTERNAL_COPYRIGHT_LINK,PanelType,AskAtOrderEntry,AssociatedObservations,VersionFirstReleased,ValidHL7AttachmentRequest,DisplayName
0,100000-9,Health informatics pioneer and the father of L...,Hx,Pt,^Patient,Nar,NaN,H&P.HX,2.74,ADD,...,0,0,NaN,NaN,NaN,NaN,NaN,2.74,NaN,NaN
1,100001-7,Health informatics pioneer and cofounder of LOINC,Hx,Pt,^Patient,Nar,NaN,H&P.HX,2.74,ADD,...,0,0,NaN,NaN,NaN,NaN,NaN,2.74,NaN,NaN
2,100002-5,Specimen care is maintained,Find,Pt,^Patient,Ord,NaN,SURVEY.PNDS,2.72,ADD,...,0,0,NaN,NaN,NaN,NaN,NaN,2.72,NaN,NaN
3,100003-3,Team communication is maintained throughout care,Find,Pt,^Patient,Ord,NaN,SURVEY.PNDS,2.72,ADD,...,0,0,NaN,NaN,NaN,NaN,NaN,2.72,NaN,NaN
4,100004-1,Demonstrates knowledge of the expected psychos...,Find,Pt,^Patient,Ord,NaN,SURVEY.PNDS,2.72,ADD,...,0,0,NaN,NaN,NaN,NaN,NaN,2.72,NaN,NaN